[package]
name = "sui-shop"
version = "1.0.0"
edition = "2024.alpha"

[dependencies]
Sui = { local = "./sui/crates/sui-framework/packages/sui-framework" }

[addresses]
sui_commerce = "0x0"

[dev-addresses]
sui_commerce = "0x0"